import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SignInModal from "@/components/modals/SignInModal";
import SearchModal from "@/components/modals/SerchModal";
import { Toaster } from "@/components/ui/sonner";
import QueryProvider from "@/providers/QueryProviders";
import { ThemeProvider } from '@/components/theme-provider';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["cyrillic"],
  weight: ['300', '400', '600', '700']
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["cyrillic"],
  weight: ["400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru' suppressHydrationWarning>
      <body
        className={`${inter.variable} ${montserrat.variable} antialiased w-full`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <Header />
            <main className='mx-auto mt-30 w-9/10'>{children}</main>
            <SignInModal />
            <SearchModal />
            <Toaster />
            <Footer />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
